---
services:
  telegram-immich-bot:
    container_name: telegram-immich-bot
    environment:
      - IMMICH_API_URL=https://immich.tld/api
      - IMMICH_API_KEY=xxxxxxxxxx
      - TELEGRAM_BOT_TOKEN=xxx:xxxxxxxxxxx
      - ALLOWED_USER_IDS=xxxxxx
      - TZ=Europe/Madrid
      # Optional: set to an Immich album ID to automatically add uploads to that album
      # - IMMICH_ALBUM_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    image: ghcr.io/andreab-1/telegram-immich-bot:main
